st3215_control:
  ros__parameters:
    speed: 4000
    acceleration: 2000
    usb_port: /dev/ttyACM0
    baud_rate: 1000000
    joint_names: ["Rotation", "Pitch", "Elbow", "Wrist_Pitch", "Wrist_Roll", "Jaw"]
    joint_ids: [3, 6, 9, 18, 15, 1]
    invert_motor: [true, false, false, false, false, false]
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    jaw_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - Rotation
      - Pitch
      - Elbow
      - Wrist_Pitch
      - Wrist_Roll
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
jaw_controller:
  ros__parameters:
    joints:
     -  Jaw
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity